import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";

import { LocaleProvider } from "./ui/providers/LocaleProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const instant = false;

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const headersList = await headers();

  const locale = headersList.get("x-locale") ?? "en";

  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable} dark h-full overflow-hidden antialiased`}
      data-theme="dark"
      lang="en"
    >
      <body
        suppressHydrationWarning
        className="flex min-h-full flex-col overscroll-x-none"
      >
        <LocaleProvider locale={locale}>{children}</LocaleProvider>
      </body>
    </html>
  );
}
